services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: petadocao
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=petadocao
      - POSTGRES_PORT=5432
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS="--openssl-legacy-provider"
      - REACT_APP_VERBOSE=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: ["npm", "start", "--", "--host", "0.0.0.0"]
    stdin_open: true
    tty: true
    depends_on:
      - backend
  

volumes:
  postgres_data: