# Generated by Django 5.1.3 on 2024-11-13 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_intents', to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intenção de Adoção',
                'verbose_name_plural': 'Intenções de Adoção',
                'unique_together': {('user', 'animal')},
            },
        ),
    ]
