# Generated by Django 4.2.13 on 2024-10-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('idade', models.TextField(max_length=255)),
                ('telefone', models.TextField(max_length=255)),
                ('endereco', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
            ],
        ),
    ]
