# Generated by Django 5.1.2 on 2024-10-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street_name', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('residence_type', models.CharField(choices=[('HOUSE', 'Casa'), ('APARTMENT', 'Apartamento'), ('FARM', 'Fazenda')], default='HOUSE', max_length=10)),
                ('has_screens', models.BooleanField(default=False)),
                ('number_of_residents', models.IntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('has_allergic_residents', models.BooleanField(default=False)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('number_of_pets', models.IntegerField(default=0)),
                ('adoption_motivation', models.TextField(blank=True)),
                ('acknowledges_costs', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
