# Generated by Django 5.1.2 on 2024-11-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_adopterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='Imagem'),
        ),
    ]
