# Generated by Django 4.2.13 on 2024-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('idade', models.TextField(max_length=255)),
                ('telefone', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('endereco', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
